### ISSUE TITLE
Buf code generation using remote plugins

### ISSUE THREAD

**Issue by nickjn92** [andrewparmet/buf-gradle-plugin#37]
I've understand that a task like `bufGenerate` is not currently available because it relies on having a protoc available.
However, now buf supports using remote plugins to generate code, hence no need for protoc to be available locally.

With the presence of a `buf.gen.yaml` file (note managed part is optional) you can generate code using remote plugins instead:

```yaml
version: v1

managed:
  enabled: true
  java_multiple_files: true
  java_package_prefix: se

plugins:
  - remote: buf.build/protocolbuffers/plugins/kotlin:v3.19.3-1
    out: build/gen/kotlin
  - remote: buf.build/grpc/plugins/kotlin:v1.2.1-1
    out: build/gen/kotlin
```

This would be a fantastic addition to the plugin as we could use this instead of relying on the gradle-protobuf plugin.

Thoughts?

All information about this is available at https://docs.buf.build/bsr/remote-generation/remote-plugin-execution
